### ISSUE TITLE
Make UNIVERSE repos easier to make and keep up

### ISSUE THREAD

**Issue by jaymzh** [facebook/chef-cookbooks#315]
Now that I've created (the first?) UNIVERSE repo over at https://github.com/jaymzh/chef-fb-api-cookbooks there's a bunch of things I've found that we need to do to make it reasonable to create such a repo and to make sure those repos follow Meta's best practices. I'm attempting to document them here.

## Lint: Rubocop / Cookstyle

Ideally universe repos would be able to do:

```yaml
inherit_from:
  - https://raw.githubusercontent.com/facebook/chef-cookbooks/refs/heads/main/.cookstyle_combined.yml
```

And be done. However, this doesn't work today.

The Meta cookstyle configs reference custom cops that exist in `./cookstyle` and are loaded via `-r`. Unfortunately, rubocop load `-r` files _after_ remote inherits are processed. This means even if you copy all of `./cookstyle` locally and run it with `-r ./cookstyle/helpers.rb` it will crash.

Further, we don't want users to have a copy of those cops. What's worse is, local disables don't happen until _after_ remote files are loaded, so we can't even just disable them in the local repo - it'll still crash. Oops.

There are a few solutions:

1. package up the custom cops in a gem, theoretically rubocop will auto-discover custom cops installed as gems
2. contribute the rules upstream. I know @dafyddcrosby has that on the list, but I think blocking on that isn't a good call
3. customize the `run_cookstyle` script with a `--universe` option that will download the remote file (and all files it includes) locally, so that everything is loaded in the right order. This would be like referencing a remote file, except doing it manually for rubocop/cookstyle. This could optionally always include a 

I think 3 is the right short-term call.

## Testing: Kitchen

This one is more complicated, but similar.

For starters, in order to make kitchen work, I had to make a choice between two approaches: (1) pulling in the entire of the runlist for fb_init in chef-cookbooks or (2) pulling in only direct deps. I decided on the second one, for now.

In order to accomplish that my CI gets a copy of both repos:

```yaml
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        path: 'chef-fb-api-cookbooks'
    - name: Checkout upstream
      uses: actions/checkout@v4
      with:
        repository: 'facebook/chef-cookbooks'
        path: 'chef-cookbooks'
```

And then recursively walks all dependencies in my repo and copies them in from the upstream repo (sorta like the old `build_fc_tmpdir` internally to FB, but simpler). Note it doesn't make symlinks because test-kitchen makes copies, so that doesn't work.

That's a step like:

```yaml
    - name: Copy upstream cookbooks
      run: ./chef-fb-api-cookbooks/scripts/copy_upstream_cookbooks
```

I then tested something like this to grab the upstream configs:

```yaml
    - name: grab kitchen configs
      run: |
        sudo apt install -y wget
        wget -O ./chef-fb-api-cookbooks/.kitchen.yml https://raw.githubusercontent.com/facebook/chef-cookbooks/refs/heads/main/.kitchen.yml
```

which actually works. The problem now is that the os matrix in the GHA config and the kitchen config have to be in sync. So how to make this all suck less? I suggest we:

* Separate out the kitchen tests into a reusable workflow. It can take several arguments:
   * universe - if true, this will cause the 'current' repo to be checked out to './universe' and then *also* check out chef-cookbooks to be checked out to `./chef-cookbooks`. It will also cause `copy upstream cookbooks` to be run
   * suites - this is the suites that will be passed to the `test-kitchen` action.
   * kitchen_local_yaml - this will be passed as KITCHEN_LOCAL_YAML in the test-kitchen action's `env` allowing people to add their own suite(s) other than the default to define their own test runlist(s), if they chose.

This re-usable workflow can then be called from Facebook's CI. While we're at it, I'd move Kitchen into it's own workflow, even if it's just calling this re-usable workflow, rather than having everything bundled under 'ci"

## CI: Lint/test

Like above, I'd make a re-usable workflow that runs ruby-related stuff like run_chefspec, run_cookstyle, and run_mdl, that has an `universe` option which causes the workflow to download those scripts before running them. Then I'd make another for non-ruby stuff, and stuck shellcheck (and while we don't do it currently, probably also black, as configured internally).

## Initial setup

We should then in exmaples/ or some simple GHA workflow files that call all our relevant stuff,, a simple README that explains this is a universe repo and points to the relevant upstream docs, LICENSE, COC, and CONTRIBUTING doc.

Then create a basic script you can run from an empty repo that will copy all those into the right place, make the `cookbooks` directory, and get your initial repo setup.
